### ISSUE TITLE
Fonts have their glyphs in the wrong "slots"

### ISSUE THREAD

**Issue by adrian-the-git** [BeautifulTrouble/beautiful-rising#1]
Certain characters display incorrectly, such as the Á which shows up as a ¡, where the actual glyph for Á seems to be under the ç. Something about codepages maybe got mixed up and maybe a tool can convert / fix these. The knockout font is one that has this issue and there may be others in the /assets/fonts collection.

**Comment by phillipadsmith** [comment]
> Certain characters display incorrectly, such as the Á which shows up as a ¡, where the actual glyph for Á seems to be under the ç. Something about codepages maybe got mixed up and maybe a tool can convert / fix these. The knockout font is one that has this issue and there may be others in the /assets/fonts collection.

@DianaHajTPS Can you just confirm for me where these fonts came from? Did you purchase them from the site(s) we were discussing, or just provide the files to @adrian-the-git ?

**Comment by DianaHajTPS** [comment]
@phillipadsmith No they were not purchased. These were given with the files, and they haven't been converted to web fonts on my end. Adrian has informed me that you'll purchase the license when you launch. 

As for characters not displaying correctly, we've faced this issue with the game cards for the Mexico workshop. I solved it by opening the glyphs panel and choosing the correct ones.
