### ISSUE TITLE
Region SVGs need validation or whole site can break!

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#104]
I'm not sure what this issue is, but one of the participants just discovered it and I replicated it:

Filtering by Stories + clicking on the "Beautiful Rising" logo is yielding the screenshot below.
![screen shot 2016-10-03 at 2 22 49 pm](https://cloud.githubusercontent.com/assets/9722200/19050100/1ec29c7c-897b-11e6-8b53-0bc6c6a24864.png)

**Comment by DianaHajTPS** [comment]
Hi Adrian,

Sorry to bug you about this again, but this remains an issue and participants in the evaluation are reporting it.

**Comment by daveomitchell** [comment]
I'm having the same issue any time I hit the 'back' button, in either Firefox or Chrome. Screenshot attached -- from the main page I clicked "theories", then "back", and this is what I see. Clicking the logo or anything else fails to take me anywhere. #brokebacktoolkit 
![screen shot 2016-10-04 at 4 46 16 pm](https://cloud.githubusercontent.com/assets/8793422/19093773/2fd957da-8a52-11e6-84d2-ebe9e4d2a5b6.png)

**Comment by adrian-the-git** [comment]
Okay, it seems someone's harmless typo in a translated doc caused this whole problem, though the underlying problem is my oversight.
