### ISSUE TITLE
Draft module appearing (in duplicate) on website

### ISSUE THREAD

**Issue by daveomitchell** [BeautifulTrouble/beautiful-rising#105]
The author of this piece accidentally marked it "DONE" in the subject line -- it's no longer marked "DONE," but it's still showing up, in two different versions, on the site:
https://beautifulrising.org/tool/schools-of-struggle
https://beautifulrising.org/tool/schools-of-struggle-in-brazil
https://docs.google.com/document/d/1X-9b3zbTPeCLG0eCOlYJ_RbqrAHUUW3sVqgKZc3P7Co/edit

**Comment by adrian-the-git** [comment]
This and a number of other content loader issues are related and will be fixed together. I'll remove the module manually for now.

**Comment by daveomitchell** [comment]
awesome -- thanks!
