### ISSUE TITLE
no link to the site's home page in other languages

### ISSUE THREAD

**Issue by daveomitchell** [BeautifulTrouble/beautiful-rising#106]
I imagine the longer-term solution will be for us to buy domain names for www.bellarebeldia.org, etc., and have them redirect to the site, but in the short term, it would be nice to be able to direct people to www.beautifulrising.org/es or www.beautifulrising.org/ar when promoting the other languages -- would that be possible, @adrian-the-git ?

**Comment by adrian-the-git** [comment]
Adding these language prefixes to urls site-wide would actually be quite tricky, as that disrupts some basic assumptions about urls being language agnostic (you and I visit the same url, but we see the page in our chosen language). It is _possible_ to add these prefixes, but not as simple as I'd hoped. 

That said, links to http://beautifulrising.org/en and http://beautifulrising.org/es (and soon /ar!) will now ensure that a user is taken to the appropriate language of the homepage.

**Comment by daveomitchell** [comment]
Ah, great! That's fine if it's just the home page.
