### ISSUE TITLE
Image for Divestment is not showing?

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#107]
![screen shot 2016-11-02 at 5 19 49 pm](https://cloud.githubusercontent.com/assets/9722200/19947942/b5ab2cb4-a120-11e6-80a8-58ec66d23284.png)

Not sure why.

**Comment by adrian-the-git** [comment]
Looks like some accidental sharing setting was blocking the loader from seeing the doc.
