### ISSUE TITLE
UX decision: how does an out-of-the-bootstrap-grid toolbox panel make itself apparent?

### ISSUE THREAD

**Issue by adrian-the-git** [BeautifulTrouble/beautiful-rising#29]
Consult w/@DianaHajTPS

**Comment by DianaHajTPS** [comment]
which panel? hamburger menu or the twitter news feed?
Mobile screen pdf demonstrates how both of these two panels collapse. Or maybe you're asking about something completely different? Let me know and i'll be happy to help.

**Comment by adrian-the-git** [comment]
The news feed panel is technically outside the bootstrap grid, so there are certain screen sizes where it is offscreen—say on a smallish laptop screen.

**Comment by DianaHajTPS** [comment]
We can treat is as demonstrated in the mobile screen pdf and fix it to the bottom of the browser. Is that possible?
