### ISSUE TITLE
Design: Abou Page + Tools Nav - Spacing

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#38]
Please Increase the spacing under stories and the rest of the tools to be 36px of white space.

Screenshot from testing site for reference attached:
![methods-01](https://cloud.githubusercontent.com/assets/9722200/17028796/a87879ac-4f36-11e6-8776-c6843720605d.png)

**Comment by DianaHajTPS** [comment]
@rapicastillo the above issue is still valid

**Comment by rapicastillo** [comment]
This has been fixed on the [beta](https://beautifulrising2-beta.herokuapp.com) site as well.
