### ISSUE TITLE
Design: Main Page: "View as", "Sort by", "Tags" 

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#49]
- The left hand menu of "view as", "sort by", "tags" should not scroll. They should be fixed in position and accessible to the user at all times once the modules scroll. 

Screenshot reference
![screen shot 2016-07-21 at 2 41 20 pm](https://cloud.githubusercontent.com/assets/9722200/17034562/37a4c418-4f51-11e6-87f3-04001d7186bc.png)
- "Sort by" inactive state of "alphabetical" and "new" should be Avenir bold underlined in this color #828486

![screen shot 2016-07-21 at 2 44 45 pm](https://cloud.githubusercontent.com/assets/9722200/17034677/b2e3e712-4f51-11e6-9b7f-53bf331d6739.png)
- the tags should be separated by a "/" that's bold and black in order to ease the eye at looking through the list. The line height should also be 22px.

![screen shot 2016-07-21 at 2 46 39 pm](https://cloud.githubusercontent.com/assets/9722200/17034732/f6fa61e2-4f51-11e6-972a-011d54235a3f.png)

**Comment by adrian-the-git** [comment]
There are so many tags that the filter panel won't fit on an 1080 screen if it doesn't scroll. Those hidden scrollbars are a pain to get right so I'm flagging this for later.

**Comment by DianaHajTPS** [comment]
hmm good point...
