### ISSUE TITLE
Design : Module Images :  Snapshots

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#56]
Please retain the grey overlay's opacity on the images of modules, but decrease the opacity on the patterns overlaying the snapshot images right now they're too faint and we'd want them to be more prominent. Maybe you'd need me to resupply you with the the files please let me know. 

Reference screenshot of current state on testing site:
![screen shot 2016-07-21 at 5 03 21 pm](https://cloud.githubusercontent.com/assets/9722200/17038780/50d6fb72-4f65-11e6-8ff8-30bb63e899fe.png)

Reference screenshot from ai. file of desired state:
![screen shot 2016-07-21 at 5 05 04 pm](https://cloud.githubusercontent.com/assets/9722200/17038803/7a3eb8b0-4f65-11e6-98fe-ba62d0bbc13a.png)

**Comment by DianaHajTPS** [comment]
I'm not seeing any snapshot modules in the toolbox whatsoever on my end at all. Is this a glitch or a decision?

**Comment by daveomitchell** [comment]
> Is this a glitch or a decision?

It's a recent decision -- there are so many snapshot pieces (114!) that we were finding that they drown out the actual content, making it hard for users to find the substantial pieces that are the core of the content. These snapshots can still be found by clicking on them when they turn up in "related module" lists and in searches, but don't get in the way so much when people are simply browsing. Fingers crossed that you agree this is an improvement!

**Comment by DianaHajTPS** [comment]
Ah! That makes complete sense! 

Thanks Dave!
