### ISSUE TITLE
Design : Module : Inline Images

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#63]
Seems like inline images are broken in some instance:
![screen shot 2016-07-21 at 5 48 52 pm](https://cloud.githubusercontent.com/assets/9722200/17040033/820ae680-4f6b-11e6-9fff-e37cc6223c49.png)

**Comment by adrian-the-git** [comment]
In most cases these are incorrect filenames in the google docs or missing assets.
