### ISSUE TITLE
Design: Logo: white background

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#68]
Logo on all pages except module pages should have a white background that hides the intersection of the nav bar line. Please see reference image below:

![screen shot 2016-07-28 at 2 05 00 pm](https://cloud.githubusercontent.com/assets/9722200/17223860/6c8e62bc-54cc-11e6-8535-e39c7f622e81.png)

Adrian, I know we've discussed this and I mentioned that I can provide a png that has the white box in the back but you said you can do that with coding. Let me know if you changed your mind :)

P.S Arabic Logo is treated in a similar manner

**Comment by adrian-the-git** [comment]
I can add a white box there, but it's unclear what I should do here:

![2016-07-29-165816_445x260_scrot](https://cloud.githubusercontent.com/assets/4494346/17266477/be5dc830-55ad-11e6-882e-78b6906a6ab4.png)

**Comment by DianaHajTPS** [comment]
Great let's add the white box, and in the instance you're capturing here I think we can remove the horizontal bar in the activated hamburger menu under the (x) completely. What do you think?
