### ISSUE TITLE
Pull all site text from relevant docs

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/beautiful-rising#72]
Footer text doesn't match what's in the User Interface doc.

**Comment by phillipadsmith** [comment]
Footer still using the old text, AFAICT:
<img width="849" alt="yellow_pigs_in_parliament_and_telegram" src="https://cloud.githubusercontent.com/assets/34128/17386587/04f7d8f2-59a1-11e6-821e-bda89c1bb889.png">

**Comment by adrian-the-git** [comment]
Fresh API content isn't pulled until you reload the site.

![2016-08-03-190148_810x120_scrot](https://cloud.githubusercontent.com/assets/4494346/17387907/d37ce554-59ac-11e6-9ea7-19faa4940708.png)

**Comment by phillipadsmith** [comment]
> Fresh API content isn't pulled until you reload the site.

"Reload" meaning...?
