### ISSUE TITLE
Set-up info@beautifulrising.org e-mail address

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/beautiful-rising#73]
> Ive just tested the email info@beautifulrising.org it should go to me right? Im not recieving. Maybe a fix worth persuing before we head out

**Comment by adrian-the-git** [comment]
Currently only goes to beautifulrising.org@gmail.com 

I didn't forward this to us because I wasn't sure what purposes this address was given. Will fix.
