### ISSUE TITLE
Design: "Home" Button in Hamburger menu 

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#79]
The user should have the word "Home" in the hamburger menu when they're in a module.
Please see reference screenshot from final pdf, although I realize that it doesn't have the updated logo. The logo and (x) should be moved to the right when the hamburger menu is activated to make space for the word "home" when the user is in a module. 

Hamburger menu when not in a module
![screen shot 2016-08-10 at 4 01 26 pm](https://cloud.githubusercontent.com/assets/9722200/17554566/2884c35c-5f14-11e6-84c5-abbb9248c5e9.png)

Hamburger menu when in a module
![screen shot 2016-08-10 at 4 01 07 pm](https://cloud.githubusercontent.com/assets/9722200/17554574/32fcbeb6-5f14-11e6-88ae-4b2318762248.png)

**Comment by adrian-the-git** [comment]
Sliding the logo over when opening the menu is no problem. The real issue with the menu placement is that when the [X] is positioned directly above the hamburger icon, while also being positioned so far right in the menu, the menu has to fall outside the bootstrap grid. The left edge of the grid ends only a few pixels to the left of the hamburger icon, so for _some_ people whose browser size is only a few pixels wider than a bootstrap breakpoint, the menu will be partly offscreen. There's no guarantee of any margins outside the bootstrap grid.

Can you elaborate a little more on how the elements should move?

![2016-08-11-213809_426x373_scrot](https://cloud.githubusercontent.com/assets/4494346/17612873/fabe6c68-600b-11e6-82fb-ff676e6b5916.png)
![2016-08-11-213816_463x370_scrot](https://cloud.githubusercontent.com/assets/4494346/17612874/fad1f472-600b-11e6-9b22-3709182c46f4.png)

**Comment by DianaHajTPS** [comment]
hmm, yes that's an issue bc what i'm referencing in the design file does sit outside the bootstrap grid.

Could a solution be that the word "Home" appears above "About" and pushes "About" and the rest of the content down when the user is on any page other than the homepage? 

See reference:
![screen shot 2016-08-18 at 9 54 34 am](https://cloud.githubusercontent.com/assets/9722200/17776355/2dd2fbc8-652a-11e6-8564-1d1dcd26527c.png)
