### ISSUE TITLE
Design: News + My toolbox side bar

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#81]
The arrow is pointing the wrong direction.
It should point to the left when inactive and right when active.

Reference screenshots from final pdf:
![screen shot 2016-08-16 at 11 19 01 am](https://cloud.githubusercontent.com/assets/9722200/17704550/5b6749b4-63a3-11e6-9665-7ce3229c68b8.png)

![screen shot 2016-08-16 at 11 19 27 am](https://cloud.githubusercontent.com/assets/9722200/17704549/5b6188da-63a3-11e6-9e1e-2fdc49efedea.png)

**Comment by adrian-the-git** [comment]
When turning the arrow 180° the animation became distracting, but I'll put it back
