### ISSUE TITLE
Logo overlaps with a border in a strange way - Chrome/Mac

### ISSUE THREAD

**Issue by drewrwilson** [BeautifulTrouble/beautiful-rising#87]
In Chrome on MacOS the logo seems to break outside of its div and overlaps with the lower border. Doesn't seem like intended behavior. 

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/4324656/17781978/7751ea24-653f-11e6-8715-f67e80e817d6.png)

(great project, great site!)

**Comment by daveomitchell** [comment]
:-) Thanks @drewrwilson. 

This is in fact deliberate, the result of a "rule-breaking" ethic that was taken with the design... but certainly worth noting that it looks accidental, since rule-breaking always, of course, opens one to various risks. Something for us to consider for future evolutions of the project for sure...

**Comment by drewrwilson** [comment]
@daveomitchell 

Oh, haha. That's a cute idea. Personally, I don't think it comes through though. Makes it look like the page has not loaded properly and it pulls my attention away from the content. But in any case, you're already aware of it! :) Whether or not you choose to change it in the future, great work overall! 

Closing this issue because it's either a feature or a known bug, depending on your perspective 😉

**Comment by daveomitchell** [comment]
FYI @DianaHajTPS @publicsociety

**Comment by DianaHajTPS** [comment]
Thanks! It's actually open issue #68 here: https://github.com/BeautifulTrouble/beautiful-rising/issues/68

With the new logo I requested that where the logo overlaps the search bar the line disappears so it does not look like a mistake. See screenshot for reference. Waiting for it to be fixed :)
