### ISSUE TITLE
Content: I think you got the zapatista quote backwards in the FAQ

### ISSUE THREAD

**Issue by drewrwilson** [BeautifulTrouble/beautiful-rising#88]
In the [FAQ](https://beautifulrising.org/about/faq) it says: "As the Zapatistas say, caminamos preguntando (we walk asking questions)." I think the term from the Zapatistas is "preguntando caminamos"

:) :) :) :)

**Comment by daveomitchell** [comment]
Fixed! Good catch, compa. ;-)
