### ISSUE TITLE
Design: Patterns for Theories + Methodologies are the wrong height

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#93]
it seems like the height on the patterns of Theories and Methodologies is much higher than the rest when filtering by module type. These two module types should match the other 3 patterns in height.

Reference of Theories and Methodologies patterns in comparison to Principles:
![screen shot 2016-08-24 at 3 16 56 pm](https://cloud.githubusercontent.com/assets/9722200/17945025/10be3f08-6a10-11e6-8817-660371995091.png)
![screen shot 2016-08-24 at 3 16 59 pm](https://cloud.githubusercontent.com/assets/9722200/17945028/12f20aac-6a10-11e6-8afd-6296e41da9ae.png)
![screen shot 2016-08-24 at 3 17 02 pm](https://cloud.githubusercontent.com/assets/9722200/17945029/150ac11c-6a10-11e6-8414-b4eecbf1d309.png)

**Comment by adrian-the-git** [comment]
I used the patterns as provided—those two are much larger. If I crop them, should the background patterns (the ones behind the sorting widget) remain the original size?

I just want to point out that this element has 6 distinct layouts which all have to be adjusted for 3 distinct viewport sizes and translations with different text lengths. Keeping all 18 layouts pixel perfect has proven to be a bit of a time sink.

**Comment by DianaHajTPS** [comment]
You are absolutely right! I went back to the files and checked and remembered the rational. I needed to space theories and methodologies more in order for the overlapping pattern to work. 

Here's a simple solution for this instance so it doesn't look like an error anymore: Can you please decrease the height on theories and methodologies on this instance only so that the 3rd row of the pattern doesn't peak through as it's doing now. If that messes up everything else and it's easier for me to provide you with 2 new svg files for theories and methodologies that don't have a 3rd row i'm happy to do so. Just let me know how you'd like to proceed.

**Comment by adrian-the-git** [comment]
Ah, that's super simple. Cool :)
