### ISSUE TITLE
Design: Hover State on tiles

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/beautiful-rising#97]
Hover state on tiles providing the summary is not activated. Current testers like the list view because it has the summary, that's when I realized that the hover state is not active.

**Comment by adrian-the-git** [comment]
One of the troubles with the hover state is that if the entire square reacts to hovering, it no longer becomes possible to click the [+] icon. My original solution was to make the snapshot show only when hovering over the title. An alternate solution might be replacing the [+] and [—] with some other indicator which isn't meant to be clicked. What do you think?
