### ISSUE TITLE
Theories, or Tools?

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/beautiful-rising#98]
<img width="827" alt="comunalidad__communality_" src="https://cloud.githubusercontent.com/assets/34128/18102469/7c1f1f60-6ea7-11e6-944e-628510851027.png">

**Comment by daveomitchell** [comment]
Looks like "tool" is the generic term -- ALL content types are in here with "tools" in the URL, so it seems fine to me.

**Comment by adrian-the-git** [comment]
There is an inconsistency in the use of the words module and tool, but one that's not obvious [to me] how to resolve. Saved modules are called "my tools," the entire collection is called a toolbox, but we still refer to "related modules" and use language like "share this module." Previously the urls used the word module, and in fact those urls simply redirect to the equivalent /tool/ url. Thoughts?

**Comment by daveomitchell** [comment]
Good point... For consistency, probably best to change to double down on the metaphor and use tool/tools throughout.

**Comment by adrian-the-git** [comment]
Cool. Most of this can be adjusted from the UI text document, so it's easy to change if there's disagreement later.
